### ISSUE TITLE
Hitting a permissions error kills whole script

### ISSUE THREAD

**Issue by mrmh2** [JIC-CSB/dmaudit#1]
Encountering a PermissionError trying to read a subdirectory will stop the whole script with a stack trace, e.g:

Auditing directory: /jic/scratch/groups/Matthew-Hartley
Traceback (most recent call last):
  File "/dmaudit/dmaudit.py", line 262, in <module>
    dmaudit()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/dmaudit/dmaudit.py", line 235, in dmaudit
    directory = build_tree(directory, level, 0, check_mimetype=check_mimetype)
  File "/dmaudit/dmaudit.py", line 161, in build_tree
    check_mimetype=check_mimetype)
  File "/dmaudit/dmaudit.py", line 161, in build_tree
    check_mimetype=check_mimetype)
  File "/dmaudit/dmaudit.py", line 150, in build_tree
    for entry in os.scandir(path):
PermissionError: [Errno 13] Permission denied: '[redacted]'

Where we catch FileNotFound, we might also want to catch PermissionError

**Comment by tjelvar-olsson** [comment]
Fixed in 3699789
